name: deno-publish-version
description: Set version from gh tag

author: MAKS11060

runs:
  using: composite
  steps:
  - name: Set up Deno
    uses: denoland/setup-deno@v1
    with:
      deno-version: v1.x

  - name: Set version from release tag
    run: deno run -A scripts/publish.ts --ver ${{ github.event.release.tag_name }}
    shell: bash
