name: Deno Publish Version
author: MAKS11060
description: Set version from gh tag
branding:
  icon: chevrons-up
  color: gray-dark

inputs:
  tag:
    description: 'Tag name. Default: {{ github.event.release.tag_name }}'
    default: ${{ github.event.release.tag_name }}
  config-file:
    description: Target file (e.g. deno.jsonc, deno.json, jsr.json, package.json)

runs:
  using: composite
  steps:
    - name: Set version from release tag
      run: deno run -Aq https://raw.githubusercontent.com/MAKS11060/deno-publish-version/main/scripts/publish.ts --ver ${{ inputs.tag }} --cfg ${{ inputs.config-file }}
      shell: bash
