name: Deno Publish Version
author: MAKS11060
description: Set version from gh tag
branding:
  icon: chevrons-up
  color: gray-dark

inputs:
  config-file:
    description: Target file (e.g. deno.jsonc)
    default: 'deno.jsonc'

runs:
  using: composite
  steps:
  - name: Set up Deno
    uses: denoland/setup-deno@v1
    with:
      deno-version: v1.x

  - name: Set version from release tag
    run: deno run -Aq ./scripts/publish.ts --ver ${{ github.event.release.tag_name }} -c ${{ inputs.config-file }}
    shell: bash
