name: Deno Publish Version
author: MAKS11060
description: Set version from gh tag
branding:
  icon: chevrons-up
  color: gray-dark

inputs:
  config-file:
    description: Target file (e.g. deno.jsonc)
    default: 'deno.jsonc'
  tag:
    description: Tag name (github.event.release.tag_name)
    default: ${{ github.event.release.tag_name }}

runs:
  using: composite
  steps:
  - name: Set up Deno
    uses: denoland/setup-deno@v1
    with:
      deno-version: v1.x

  - name: Set version from release tag
    run: deno run -Aq https://raw.githubusercontent.com/MAKS11060/deno-publish-version/main/scripts/publish.ts --ver ${{ inputs.tag }} -c ${{ inputs.config-file }}
    shell: bash
